name: tf211_bench
channels:
  - apple
dependencies:
  - python=3.10
  - tensorflow-deps
  - pip:
      - tensorflow==2.13-rc1
      - tensorflow-metal
      - tensorflow_datasets==4.9.2
      - keras_cv==0.5.0
      - numpy
      - marshmallow
      - pycocotools
      - wandb